"""Regenerate src/fplotlib_colors.f90 from matplotlib's named color tables.

Matplotlib accepts the CSS4/X11 color names and its own "tab:" family
wherever a color is expected, and users type them without thinking. The
names are pure data, so they are emitted here rather than transcribed by
hand. Run this if matplotlib's tables change:

    pixi run python tools/gen_colors.py
"""

from pathlib import Path

import matplotlib.colors as mcolors

OUT = Path(__file__).resolve().parent.parent / "src" / "fplotlib_colors.f90"


def collect() -> list[tuple[str, str]]:
    out: dict[str, str] = {}
    for name, hexv in mcolors.CSS4_COLORS.items():
        out[name.lower()] = hexv.lower()
    for name, hexv in mcolors.TABLEAU_COLORS.items():
        out[name.lower()] = hexv.lower()
    return sorted(out.items())


def main() -> None:
    pairs = collect()
    width = max(len(n) for n, _ in pairs)
    lines = [
        "! fplotlib_colors — matplotlib's named colors.",
        "!",
        "! Generated by tools/gen_colors.py; do not edit by hand. Holds the CSS4/X11",
        '! names plus matplotlib\'s "tab:" family, which are accepted anywhere a',
        "! color is taken.",
        "module fplotlib_colors",
        "    implicit none",
        "    private",
        "",
        "    public :: color_from_name",
        "",
        f"    integer, parameter :: NCOLOR = {len(pairs)}",
        f"    integer, parameter :: NAMELEN = {width}",
        "",
        f"    character(len=NAMELEN), parameter :: NAMES(NCOLOR) = [ character(len=NAMELEN) :: &",
    ]

    def block(vals: list[str], per: int, pad: int) -> list[str]:
        rows = []
        for i in range(0, len(vals), per):
            chunk = ", ".join(v.ljust(pad) for v in vals[i:i + per])
            rows.append(f"        {chunk}")
        return rows

    quoted = [f'"{n}"' for n, _ in pairs]
    rows = block(quoted, 4, width + 2)
    lines += [r + ", &" for r in rows[:-1]] + [rows[-1] + " ]"]
    lines += ["", "    character(len=7), parameter :: HEXES(NCOLOR) = [ character(len=7) :: &"]
    quoted = [f'"{h}"' for _, h in pairs]
    rows = block(quoted, 6, 9)
    lines += [r + ", &" for r in rows[:-1]] + [rows[-1] + " ]"]

    lines += [
        "",
        "contains",
        "",
        "    ! Returns the #rrggbb for a name, or an empty string if unknown, so the",
        "    ! caller can fall back to the other color spellings.",
        "    pure function color_from_name(s) result(col)",
        "        character(len=*), intent(in) :: s",
        "        character(len=7) :: col",
        "        integer :: lo, hi, mid, c",
        "        character(len=NAMELEN) :: key",
        "",
        "        col = \"\"",
        "        if (len_trim(s) > NAMELEN) return",
        "        key = lower(trim(s))",
        "        lo = 1",
        "        hi = NCOLOR",
        "        do while (lo <= hi)",
        "            mid = (lo + hi) / 2",
        "            c = compare(key, NAMES(mid))",
        "            if (c == 0) then",
        "                col = HEXES(mid)",
        "                return",
        "            else if (c < 0) then",
        "                hi = mid - 1",
        "            else",
        "                lo = mid + 1",
        "            end if",
        "        end do",
        "    end function color_from_name",
        "",
        "    pure function compare(a, b) result(c)",
        "        character(len=*), intent(in) :: a, b",
        "        integer :: c",
        "        if (a < b) then",
        "            c = -1",
        "        else if (a > b) then",
        "            c = 1",
        "        else",
        "            c = 0",
        "        end if",
        "    end function compare",
        "",
        "    pure function lower(s) result(t)",
        "        character(len=*), intent(in) :: s",
        "        character(len=NAMELEN) :: t",
        "        integer :: i, k",
        "        t = \"\"",
        "        do i = 1, min(len(s), NAMELEN)",
        "            k = iachar(s(i:i))",
        "            if (k >= 65 .and. k <= 90) k = k + 32",
        "            t(i:i) = achar(k)",
        "        end do",
        "    end function lower",
        "",
        "end module fplotlib_colors",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(pairs)} colors)")


if __name__ == "__main__":
    main()
