! fplotlib_glyphs_data — DejaVu Sans outlines, generated by
! tools/gen_glyphs.py. Do not edit.
!
! One base85 string holding the four faces as the font itself stores
! them: quadratic contours in integer font units, deltas coded by
! magnitude class, outlines that repeat between faces stored once,
! and a slot table that leaves out what it can work out.
! fplotlib_glyphs unpacks it on first use; the format is described
! there and in the generator.

module fplotlib_glyphs_data
    use fplotlib_style, only: dp
    implicit none
    public

    real(dp), parameter :: EM = 2048.0_dp
    real(dp), parameter :: ASCENT = 1901.0_dp
    real(dp), parameter :: DESCENT = -483.0_dp
    real(dp), parameter :: XHEIGHT = 1120.0_dp

    integer, parameter :: NCH = 281
    integer, parameter :: NFACE = 4
    integer, parameter :: NSLOT = 1124
    integer, parameter :: NOUT = 499
    integer, parameter :: NCONT = 720
    integer, parameter :: NPT = 11343

    ! The code point ranges the table covers, and where each one
    ! starts in the per-face table.
    integer, parameter :: NBLK = 2
    integer, parameter :: BLK_FIRST(NBLK) = [32, 913]
    integer, parameter :: BLK_LAST(NBLK) = [255, 969]
    integer, parameter :: BLK_OFF(NBLK) = [1, 225]

    character(len=*), parameter :: ALPHABET = &
        "#$%()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz"

    integer, parameter :: BLOB_LEN = 33705
    character(len=118), parameter :: BLOB_ROWS_1(100) = [character(len=118) :: &
        "#?[C2=loMc^tlReFC2.FP8%L8V_GX`*A/n?@I,@*`;tjK@EN:n@@TWQ@$4jVT``;XiSE%?:+8$XShvCrY-C3DJLG*f90a_`_j`WU5^,eKqBOMS=UhQ3veG", &
        "d@>>*5oV9[DY(+`$8><GVpN5xF8tY_aZs;dCsZnA1A1B6Mz#V+FraLCt/-*:Y0NSZTYeP1RM]heyUYXf(jLftUvQ[zQ0(PXu:wx@K@-`3.[8EIajIILJLu", &
        "@(`coT`c*i95dQh?XoQQYR<mI57662Nuy-?[RkCD)Go5R%8;(.9.YpBY%oi0zJiR52AlC<?kqsTNjJeEL/FF^`2cHH09g2,Mr;:Xqmzn]_:cdmApcSBY*0", &
        "S0sYGl*pBWPAKp)WTk.yUvO5ZaX>SJq)=.EN0hC6Y(hCew>v[0vhGXcb3mSK>#uKABMMd79RJIX$X_JgpEyfoY#c:x+MB$;)lpVa#fXA:XiYbQ9p@`SI#X", &
        "XY>;J_G0fz^d7uw-87_pTZLV1=ywd%T]A+g(8qwi?kQ[PS0+mH*(K;-?P7sU(3=_x3W-bWhqO:r3k)QtNF:Yykk1fcZl6@G5F$@:85uDTkSYZw=2OQ/yz`", &
        "#*vnon`NwV>bdItSC<-XFUM`QFsJiF@mK(tfwt>R.<tzpBH3a*ES(U7^$Kn@6pj#B__f**h>(:-)FW/tVVq3.EW(2#:@F6K-3f28qW]AKIxu8U8awF7bU8", &
        "wDfyu[k?tyhh;CX1p,9ai=>fZ-e,9WxcA]Phs0__OS+rgu>tI>D+C5d%Y-aKX+lGfDoe2(iMQvv?r%c)NtNk(8mfBKuehvcV3?d^-%J)p.I1O1ycAaVmG=", &
        "[X(afF0.m]H;Z?kQMnqg8CE1Xh8qeY)OZznB%+_+<NOTD32:M2Q3sAoO%;L2[Jh/00lu0oh.G_1M#3?`$fg2%rs0AZ7IR(Xw#?6LoclJq*hrGT<JRn?/(w", &
        "r4hUiR1U>5x<,ldT+b/*W]>_502Es(8DCJ%KE6:=W,Zs+?S[JhtIH#:*@qm2Acr0*sHRg+lQGj1ke,Gn^/%6dtFQD)_T3*k:Ix6y34p5r1-hcU,#dG%UR9", &
        "RWb6d*4_tRnhLet4PMi$`0pw(OLmZ1v*pmMg>Q>YQMOvba^NqDvgL.h4l)pd-L;OytLr#C%IcSM1L/2l=XEQj%UfI/MTF_:FoUn>wtTViTBW00eqjU/$`w", &
        "oG2j*NKOYHY0dGrOfaFx7+oOs:nvgN;4p?utqUsi)lmSf+NU6RbXUC]]D9wm@kQgi+9vj+L_@xoui(iX4]y[5=5/7?Pkv-nA]5%P.(MYM:UO$g[2+[q,sf", &
        "hYT,kdpv<qoFfZDWC$L,oMcwC4sj><jJ=QQ9z*I<pE?DssG0w>Co:ZSVS-c,5YP0/u$OJa*22oVDbgc_*mKX9XC5a%%nv*wq,**,Ym59x6oJBgXaJ;7im;", &
        "/*P_$uhBGSDd<<XX^y8(r?9j9nl7?J?^x<c(-xPR%aCwK__c)ZT57P;%bHE3=3G.)N_Xg.kiMK+PB4W*9^+X2nJ[;2l<p`TK>ydOayU>V`:pSPbrRvQFKe", &
        "TqOuxY.^`-X1r>wK13c(HFt-e8T1(3XgAo-zs</D7gApJtii+SDQgLUKY]X3F1fr67;9R#ypgCaj/+_Ka+xj`d:@h(n00/++;:[l+?y>%;[FMTN06,qqBD", &
        ")BUbgau>=?29L/@kF[/7U7.qyTyjt:LTEk$V<+*qYNQ4w2x70>:zj5619m:<F`mp%[0]Acaru#qf/BEp#2cfmdu.t.9wZ(d`0c-=(o;2vC.X)If5<Y8w`T", &
        "a>cCH$VLdx/xZ]Y0S3@R+<X2]Ke;?yXF;pn)$^]62c9/lIA6?RC:MfFVgx=,4ZudYDQ:$5C=2uOTP.poYAJ[iXz6H%wiMYU_KXWJNM5YVY>iqdZ,$Tw+([", &
        "LG*>G9AXg5i/J_idu=u=>=B]d3Yl*C>stCiwJ2,tjlPkG;#Wvs.^[cNsb%0%%*a$3eX3OumR3q*1s@?4*c4HxlGh3Jm(%nxD9Q6=qdQ?<k,++q.Ykc$hHI", &
        "u(E;fwg#L>jHl>`aVE%S8h>Z[2>[KprnRV;PD7T?0+IC<GJd;#d$g:SE**xD*6vQ=2(R]%W,l),ap8k;:idwmtD(Pv/B81C9[BK`[l:gC>2?Ud+Rd(hwfp", &
        "SG;(3vl8SJ#-bJx1.zww,NZ]3$wEdvv+Ypf+IV8aS$2cOHfWMer>,OICM4YO_/]542]s%FNZ5kz@K/-,P>.Q[n?h*Nlbx#sl1XaF)(^5%YAz.p7Nb>m>J3", &
        "s_H;<P+m3cPQ@+lErzi1)Xe+keA_,35;eb79jJq=;o_px2`9Z$pRNGEA,(2wk)PE_RZ4(8dc_tK<JvcI8TG#kHo`+QH0CUYRP-V`Id@1$._`A?vf=;F*(p", &
        "WM%Z((BKBwF0*mgA,KugQcH6E@e%9uty6[B,3YSiGri3Dq_Tp.Defm-@Osc>Ta5m-gE049UL9h/5Dx>$)(ARTd(mSh`5.K9Eu+b:hMoxt[o;@0a%NQal+F", &
        "g%qNJMc1Xa>Z>2n7<PtNHaF](Va@QhLyBTMMaMlryGWTAvl0SP(Qx,/tXs0WD<mOlSm2mKLz7_lHNsaYk<GhSR/FVnKW5rYQ6cmx?Z@2v%8;epg6(_:t+9", &
        "id`cj9?]9OF:TPe-n9%G$UD[^;#ujP/@J9u:6G3><3DUb<%E^)PCO#<PZb4fjOAG%ljsTbF[g3Fo^HrhHyxiu,V^merhuvCvM4$.Kyxz1oqfw-DEF#);ob", &
        "FlTU49v.v.?gyO+0%_e2c]]i3eWL];E=[Xx:p,cH8B`S4x;H2erKJ3u?d55E#2Jc]P9%mhp3/)l45uHp^VGtzmj(iEcWUAjX##mNeRLite2i.GFJ=Yi,E>", &
        "P5LEu:SxO.7(YXnCzhEG1E=$La8r6(1:z8(g:+(iA4.(h8*;d,L?TnlOaxkChP)iCDwc]?Nsr7BaZi:/$R%19VQegIo-t_UAkK3D9<Ge3>)`V`RY0>MS6S", &
        "ZVexnAHYwtmww#RDKX#O7sK1LW@c^ySb>q100ejLOWv0h<pBKMAcq;z.Z1dlkS6U$IQji$lkmq;JI+p>:-CccQH_iNbRl^vX3x%LHXj+%r9]C::<ywwMf.", &
        "(0[o?t%7>9yVRtj<?q0Vc?Bc)fL^68>`r.n1c%lJ3(gnn+7k+):v`VVl;@W,=3k%_aL_XW>L*)7m8td/2EM1Vmw_hy=#H9PrQ7^5V=67$t?jnK@c(I*222", &
        "]o,M=ktW#08<t3?tKZpW8=p9lZC8(G%s[?`3vWcM(3UR[j[pQYu[rT_2,bIqg%zH,RgO0j1]j@MqmQx3?cm8,BJ;ukg>,UQhPxfo9-A[bK,]7fb5F:ANNC", &
        "Rk5aVe6VaN24.OCO=uEl21#Red+rZI0Y1lS)bQWg*M`GR4FJuf]X<ME<=588IbTjNHII%Q7IMB`3XUz5.vtEaQvhm2E5^JApfBC$3n^[<DFl%C_Su.ppR7", &
        "LqRGVs%9;QSL85<4ypbQs1U7^^]BFr2eLO%NrKD.EqTY%hR>)rVL8Eb7oP-))=Y@2zeB?+QA.ir<V<(;:2<4RgFPbRGbekV0:HQkI9c-7^txjrX.rqTDG.", &
        "_wKHy)X;;sI_cHL;]3-SbWdAySns3hWaqu#l9,y=1u`k7;D$Z*ANV#T0P)pqN:ZkTeeT$<8oOo70;<8Y-0WNCp?NN/SCqlF2U7QB2).a1)AWH<1u#O%p=I", &
        "5BE.D;Gin6QI[%8qw0)ZCo<D^,`eYby(J2v4i>aCAm2s+xXUx@^/jy+`M4MvzAY=#CJ[w]F_b/w>lbgTPGRJ.?LP54r.fZVYl;x-@hNcw:xTg=@l<tBos-", &
        "(9zZ?RV-w1/Em]Ds^_x1qBhLusugI1a3OsM./r<Z3ViW0.,$.,Ci?C/bsFF*)RLi;BrEV>H.n43MY+<Yms;h?XFxHI:]OEaZkFEOgd`yDE(5C_Yq)94P>^", &
        "EE$TZO]qW$(1hy50hNc6_b,_sa:BS_IoTg^u%l:=B7e[xd%`nugV</g?crrJ*@e-wuiY=D2.3M7Z-#r-f%oFp54BzjapA:S-ZQQ]zWM1r46dJ:^Km:+c<$", &
        "iQesljzL+R^BEtzuNQI9<ZI@s`0<A@uX(1YAd1w,>eo?t/#V1r6XGv$6X>G:-Yp[WlY>-OH787^b#n22c8Und@6QPr_^1l,FJG^LcRQ6=b0;I9<ZI@r[/Z", &
        "Ajv%/,f1l`_1Wq:k,.V%+FNWUF9o-mC(mKn,gu9ztiY<)@_QMj$zw_u@4W_jA.)ov-*#9bfxMl#Y/50u:3[KO>)J2`*zcmaH^WLI*O2ed:B<vu<cPEK*U@", &
        "?-:$9vc^a$$=?$F;]%K=d._Nu#;)$xvU2W,5?ZeI2o)+eRN[BN5GVhdYm5<sWPJi,C(%u@5jpk]48Zs,@=0`oHlDp*CtuVOE?+Lms.04P?R39i#<SqICJ(", &
        "2-KZTAj?[0J46T801ck`IQagI9<ZI@s]>=BuS3#8GS<#9Df:eQu+wL*@HSfdNY,A@aNHlH<3hNO59?[EP=6cfCbv;e/>0=(VH.p[t;8drSKd845vwI+BtD", &
        ")AmzIlY^I`1lkHj^/F2jAEjBX5e>B<svJ(#R;OczR_Sw)^YwJX)6f/7M^;`44,[C30TAz@);#fZ(X2C(Uru@v*Jr?`WdFSb1b_fLS1CaF0/uwbO(Ns7`#r", &
        "0%2;Ir#0)$%k5q-N@:1I#T%>G:L:%zJ_mfN?Rs]/DqnB,7u#t3?_M#qKvmm1]:U]F<uofJPbJnW>f3rX88#0p3YT$oKcwodcz9Qod%Ig5km,*]p/$Q;2;M", &
        "6I2AD_<EGkaq0l#E<N37.RIkQGj`DUOLao:>MEwH1d4jA<T%>bNMHl^*IPtJ#kEtQdO.S8baCiuVvz6=2sVnE@j?Y5d/>QMFaAt<[Ao/*OR(ktYR9R>[>+", &
        "q$3+WhIp=RV2huwgp5MW:.#T4fT6Aehi*dro2SZTp.-7=%??9zVDwAqx5YM<zLsfCg/3?weBNiDK3^p]Eu0KI]j1a,zn9vBDk8xWNI(0WQm5EDq>M7eIg;", &
        "1_w>.,?X-,KNz,r]1.#Zc3S]Rvh8Ie:5]aK]UgLOT]=T8E45v-o:^Vma6XH/QnYK/r[bbi>BoKsViF^*A7dzW)dajv5%X%vBLvF6Y>oRQ_XceEIbfAFlx.", &
        "t^[gBhklycMgT:U3nZRVba/5qZoz]4$@X43wLMy5Cdzd)toP(3n)oksb)_%P.IuWW$7mPLkPFO@D3xMgP#h9w*`Tq3aU<uaD(rA_RH8yEM*Em]+GWMkYFY", &
        "4.0($5JcPtP%P1)f^?ABxIh,5S7*%$?HvA6=Kgn48EH>q=vYG>Jur_,)y:f/^)`CqvB`vFEaUM/4H*s94AIR_E%*$#eVr(u4UmU8dgoQ<TRK-[$9DU0*ny", &
        "OWH=rl)O7S`nthwS5F-`7Kw(cK>iolatLQgg7mrdJ-=rMBJ*jG88W74LLBjidNB6VW,>.5XR`4j>IZyVJ-;9PEIUyO%eB:]i9%HN?#haNk;rrME(3aZgJQ", &
        "JtKk[#wnoJe*Zh_<<G(K%PFMQZ$[@@Ev`h/aH(FDG(Ky/Rjj2%>On*>kD?GVo^C2wVIQOPKb<;%MpAK#j2isJ+i=knb,,%eoc^k5$wIk7m?JU_^IRkMF4H", &
        "*OwP:bC`JV9P$cZhdv2KyZWj[Z</p[F*NM?s<%.73x/?=YyGa7A8#2fhmrxBM(*(<zKq`2]l:w[h)b3)Ku??+n/-z@?S^-c@lKN*k4=#^u?qOUCg=%0(7o", &
        "i78/;a_*=%eKGmT<R:m-R:b;uRTwAfRWqW;?[Oh/7>vT+=e=05,8C[YW8(xGzNPKgBtr4KpiR.^LfMhY)1e@efZfxx<>m>0t-n-)f,348:FHz#FAcFeNmX", &
        "YLki(E:]Q2VwopX_)V*YKt#h5sF:6wTxUErDj60.A?)AiC#9V,oUh]rIXFFcNv)XdOsTORY34+A>xPZ/@f#Qm)dO#:%h>2sn=wQ_lyh$x1b:D2;t/O6V%M", &
        "R=YH(/)q-XOt38@g(rmA0>JXC)_v@IQZ#Xv>qU`BJBE/_=5bMwE@>=CPFmyxq:6#h7@Z)U)=KWtaDa=RC-prY_ck7TEN=z,HBPrvW7fU5AYydXAM-5j(y-", &
        "Oa3Zwh7sS#t18v,nAopT)v_(b((PO-O7Ns`zZ+/2J_fMxQL3;BD<VtE49YtOQ$o4iyT=EUewpV=,6G8g/JCr>IqbX3erh?>MS8qQ1hL*>,3+W*jy+T^0]3", &
        "m6g40xZ`lq*%hs6uMFGvVV@mq_p+a<YIn`L5R-MOWjm$(wTAhvume6^?]N/dDH:?Y*`W`Q/%5MY2WC:N6$HG>%^?v(:a-gHR.R]e9S)AU_TK?VVH,k)$1I", &
        "57RCJ6PmwkN:<Z/n/y>it)i<qhQKy7w]C(wD)#JPn*j,B*wfu_ZIiyAwveQ?#;@<qOdclZE7*?cPT_IME;5w?fpY(:wW)vdW#4TZy_Uv_%Y##zoNC#so+D", &
        "6TR:6)Tdj?3VX-GIt=o,P,gVN?G+;TbT$M.gk(15rbS18j7umLvNx-@1Yl+pV(M;s/zz*UfxI^h/Vx9D9.*F[,5:nW0fmH)G6u(S0rAK0r:OoFX@3*XQWc", &
        "B8Z%OUP1DP/<1g4?/.NrsQ=*dM5S@-+K2]/*:Mt64stcb=MSM_Mn.SFZdb9xSPHb[ndGA.fKW`WT1P@HREA6[,fG<$[Bbb<M0V$lfml>ofpb--nD00JuGv", &
        "hw<7u-+H5aa<AM`f7U9L%R:>j(@Y`Jf)uk4E$)up<ZBefnqg$@@a*BslsLh-z)*<Io4KVBdJS]CEvAOa->izgIGry_Vnr<8M51(=VbRpWFr0I]7Nx4a-u;", &
        "/W2_8?3_F-%iZqSZ@0V,768P2,GZPtVwvj),M9P>-Je<UYEI(Y>>IdH,`tkutu[hu7B86hPvy3`l%QUeaL4@2`c1op)ftp1mK_P7.[;KDImlEcu3[Y`t_@", &
        "@eco0EdCOnf%T$,0v+%,OkmH`VOJm.rf#_(_5#$3gtOCN63o+kL26,F>ec6tZ8YVuBK$uy1dNtBsQj]]eFfh0kf08D<#x^0mg2io3uQnwC5z4Mh(@^l1D*", &
        "#UG>iEOqe,AYdaXXKLnr]bkQET1*.y61*7Zk@0Y%Gzw,%9>[?>;+@(v/Aef^iI>LUuibI?TEIv5#BV/^8Kt:DZ7/+:tQeF[y7/6OFv)eu(lWUT:@$E5mPC", &
        "=itAf6pGQ*5j*E8V;o?IH5gr-gUs#@oXl^V4AkWHO2Ow/q>-GCZVexx)*r#GFhtyU0yv=q1ze(1UHwB#Nlv.W(alC?]2i52WHw5O3B;zEDpsuh,zo.,O0F", &
        "5Z;5jlXe:7mrtOS0D>i[WM:#t_je^arm4ZSg`w.k(UWFSlRPFPa,9Bs3@$d%h>N:X=epdIeqEjSaMgDs)nQvHUhQoCg4Q/%8@[45yfSAcd^4t7@q^v;@ra", &
        "N2a-?k],TmA4tvU])SAOSflhecITqp_U0$/@nk^6)w?RYUORg*lL9D*sq>z,oB`HfY[1KA<uhObgAW6PDW)>UY.[:1*0@6-;<-tU^80bMG+)Dh2Tjv^,VC", &
        "xFC(nQ29Nnh9@<`g1PS)twxP:3Pas^K%hbvJs;]Sbcp5Xf@_n%%5OGk4C.FhOZArqW;uETv;TukUSYp69+/1ow%uR+3[g<VR@#ZV[70OHW_(UsR3AFBfW#", &
        "]QcsB8Ai*ZI>ooDP9VVSIAwi;,,n+9]1X@pKQJ5_cHU%syR%wmuQ+cj3Kq^QH#Nd30/=qxIxP`C8;0i0`Wns:g`]9QQl4jBG#WgOZYQAm:eI?,Gi,9k6=9", &
        "XqdcfpHzhf@Ip@s7@tD;5cNz9Pu+R@]2dFb*)w28iu2kNs:+>I`(J/(I6`[_pLlnSF?Iy?7s6qZ3;>ycwbF0qH?azcXvybrP7C_]O]R%r??1U.NQxK(qE`", &
        "8hL;85#5tz]6Tt*0L5UuL?iLfxAiL90l2o)uX]Jwtei/vYiTA=<tJa/895kd27)QTUOHgTcml/ASX[@7C)1F5VLG::PT$eOCPCtjnW+sOWf/T;4bPy,bed", &
        "-/_[Nn5175*_VYT=@x%OChr>FP+Gz<^KY.:dG=0WuvzdRg2#@>m$)b>>BQBcY`,t%T>.kXtnQ*Yd`MnfbwgFwb3PCR`iXzgdCDhbng:3Lw2qHkiLCXLgdo", &
        ")v5pF;jm.W:8VBk4v[4C_56z:?+WGsF?_yACEzOdVbK7PZ]Z_NGahj.?Nj;ml?5k12E$OyeOIRHDQ>y^CE8*3b)5r71pC4RwTq*A?L82UqGtf8;$+J4toA", &
        "doc`F@v_7sksar_q2:mD@5-J>8fZVn*jqoSGZagZ#B+H+NXlY_Ho-R,l4oL0=Yt*GlE$D9=$>nx,@)9g,tY:/(90gAT367Yk4:+L3KNQTJz%:=S8/<TyC/", &
        "=OqJHXQci5*W_t;,uDV*LWYO/mI^(4g[`68+bzdT,eS_[Kr;7V2ydH4DpPmMTj#`Qu<w)TRYj](kk)=C)Ub2*ker>y[`R3*9k27UaP*YOPCHU`Q9)1.0Hz", &
        "e*;gF[?Vh,3yj^SIVb2.fADweRUwKhthl]>rSCOlNwLkT;l0FSr%x-H7Cl@z+Z.l4:>4xvMn0Mf/RuCAyz_[AQ>BtQ9Ta_-zT(rWwKB73oi:@3O7ULZ)Eq", &
        ">pJ6Y>9o,WT:5#]:U.*dHEp?K41Hy9w,QF$YYoDlf;]S$YSKi+25,e0h730*y#XWJT?rSbq/SKataVMED/g3H2oUzEDK8kaR58G1JaVH4w7=uWhsG/;rc,", &
        "[YFMAUF9u$n>#*[/2/Qb`]OKz?(DtJ#1SRRc#K*PLeL)x[feRly5qO#PXmWO$Khg9jsv3k>%b$GPEXclE+<G:J205M6nC=Xb%%GFk*x8)x5N#NF@y/;SC?", &
        "zM^eO42AWLXI3?Od$q1X,TJkjsSa_xZAATaYJQj-<K4@6GpJU,$je1RvPAiaR$^UwDUKQKq<t+gH[Z.4(g=03TbOF@eK5rm@eiR6*jdN3jy$32/naO^KK+", &
        "/Ndd/Xxyxrdg*?_*x5vPWc%^iV;0(_Drtcb+6G44>OuuNq_X8pBECdxvY`%-J]sg5:iAF#WP+1g8zoG(f]*Wk<5ePbKrKZv:>D]#1KpDo?3r9*maJ@3gmB", &
        "Jwi8#ZJV6oi8tLU%nS>#4Kd.l(D)nU=*G*qiuXiG+u%-Jx#T$L5Le4-G5,.O>WAml,P<:;$L]_OFL>,3QgS5pC[ppBzIuuQ;Sa:rpJmVkJWPrmoZkNz=[[", &
        ".ZE.mh(+lp[Heq9C2jpZfXw.WW,QemENcyAQZdqUZGPd+#VhR[DjP*5#Ro%=*fOToP1EFGW>85%qzvo[N6klsOO@`<gfw65m3D52#WYf+0Vt?SbB37n_zH", &
        "X1LoZ+dkmo1,N*$y:URg<7$dlK0VKAtf[ac[g]YWaS9xYq+L)i%^YR#Lny](a]xADnCq3=gbLHXaVL3Z>7CoHvAzPwp?oETC7-[%C(TWjx2zim]W%IWCP*", &
        "c#b.+9BO*:0(OoMrp/4f@Jk9s`C9T#pL[++7sS33vga^_^$Md4-NJ%$FtbQ+]qq<@m%Aqde5$0JGFwQ2#uF1fr5j;v=YUpK28x.n<gT@5NCe(%M(1Rop-s", &
        ".Id,>FC5PEjJv+LS3M:*Tob<f*gTZxad19DsMMTrgf3DUJEBw7SQnr%L7J>+_(i:+-gpB1E+fea*$Xxg@g#u+jvq2.*l4iG2W0u35mOq]2_Tn</R3fCDc1", &
        "O7U_3P4+#d0,/g6rxXl^=u;VG+IZ#+4S[k>PG,TyUzTHKh-=OS.qf?^F8[xLhn?%kA+DP`$1])M]0PzXhuXi6ISLcdkFu6o4W*U:Ur-PYbhp/sW=29bhuS", &
        "LhWZ(1C,/<@HA51MU@i%RDph?(P*yj+.IBkk%5Re-Q(qXFI(Q8Z96kQuT_:OmC$$pwvqQWo^,tI#>03ad4<<iQf(IEK2It?4=$@+<H[/L_7`.PR30Qe(/y", &
        "--`2yT*=T:9r5<Sypg_W.IqL3(b31=-gdDF:uDCyz<<uujrRX_M[Co]`Xh8H(O,HUUfcQ]n=ek+q0eJ#$tcfKm.3L>l-)GsWl7pID9Ax3(YehTs;IeBZ;+", &
        "e#-,mpA#;+.,gQjOMPJYD;qVA<0^EQl9h<G0.nTZ_g$XdVb.6#j)jW2iWn/L7I3<slsGG#8bpfOG]7.tfKyj<OyfLjk,<?-7%R;4FgZ-Je4S_IjTSkoPm6", &
        "?h8.GVJ;AdT>3YHXn$G+0Ize+md[<VNtixb.`R(+-cU:ph:]a0guCFd<4tN#A/^Pss3eq$th%5qt_jf0t_adW4d2tEQ174TUPWY[$>;t#3EJ6Z_G8d=.2-", &
        "-?rQwN/ho^/h_CVh1m(n89mkkd*0uLZr>far?GKsbD`9KiG0_iTXC8$t]CuwHdYSg;FkJc1sqneh*JHnPy54=+O[s;sHjEes[gp4)i_?RZD+;h]<fJ`3f-", &
        "_mF<IGM1bW8@$sTc:$y16)G<Jc$stPhqO`:NQ)bKCE$Od-c)c%g9%sYd<k$GZe(bHh$yVf5EE-vl,_s?qy,_Py1xw6p<IMfb#oX@LtqT]ke_Xa0Zwz6;10", &
        "(8+Sejs0Wx]XsA<q9.c]P:)psjqRcm:hudDQulI?07tWYpm$wXz@oOwRo*x;/$inL.]an<?4A1,BQXqc?6?p$naup*N+_Fun=OO5cM[XY?_Ap)87om>c+?", &
        "[%bNOzY+Dp]2H9qqkyc<9[Ujqj=2GL0E#_I%]Hak^zyB8ybQifd2_JQ2:7u?Q#7X;2,7PSCl%`Dk+>OZ82j%DTFu;>CTzOW>EbHMp.T1;+QL74ft?vg`P[", &
        "Ad*kmKaUKpcc,GH`3LH]^2=x>crNW-K)LmQj(+M/[u-6i7-QMN-V0Ikjf@g^c(3HP[e6m>P$)`dpGKk$5/<;FO/^5B:nK3/NO/R?hIwcI)N%X))5[bx>iz", &
        ".j^fN<Rk2O/4P33-F:3i-$R<9D>a_A*Y,cbhWgu/p]I?(;[nV9j>fL%0xcj-Q3LkYzD31<c)uMMnk?7`z]a/`Yta.2+vT+bXO1ru?>3qUbYNN6yP>Jcclb", &
        "l`l<1m(mN@=Y/*]+nwj7-3fHObc/0mYdykh#u>Ik/J_R)qxcOtwdin.(462d@^@`^TLb<lxKP#pl-PbE5$Lyt6c-4_?`I2c;84:lPU*:^:VupOxLB^LN:A", &
        "<M[aoj60Y*6[ah1]DJ@06v9;#+<_0Rl7(^=U(`JEEEBJ0enb=9fKIQ;Q<p$U?+O<-yJT;xqYGvYciC0Gi1Xa?QJ@=cCHXMaj:_OzoS_Ckde3^]2Y7<swhV", &
        "]0KdNMQe`YZwmR=IV)jf/UNQaoaB#aaW,hG,/_5ml;m.,)T^O#lJEPeMJ)73G1q+Q0)14j6@7sF32F:sP0ZNNEf/LF#hK4rQT,etVi_HidiYAjN`cXw7+5", &
        "gl_?n0_B<)U@I;>#^vwq_M-*O?Ec#a6#<M_5G?4$QC(LiQT:K/fxY5^1d[aelji`4>9+Z51G.ir:sO%)G,4Y.<x0BJ1q%+p0E4Ir,7t.d;QOTg[-:Ls2H*", &
        ":n4JK?(QW;a:p]UrHaL]*aAEw9TW>ty(3(zRP#E?NN%$=xj+HsZAm<U/X:pP<w2>U/1XSjM4U,E]WAjmO=/oHTvXQG5>hUa4zoES%?p-iqH*vZscVAx^$;", &
        "4$dFeHJiUDm]eq+Gd[j[V:H><mPkO[K:T+/NEl7@?2j=<Y`A+jRO/Ur^mM28*DmbNlH-2loO,b7Z:9IfBVk7t)wWb1;;J7/0R/:3[mx0]GVy6fDP<)efR6", &
        "bP9C7(k[glGmcxuTPDnT[x)Ly[w@KjP@*;+[;5;Y)M4<n4QPw4(G+z?.Oi=hyGM$F[QEtTn.=sQ=/h#nl3i7_:.gEt]2I=67(><KDQ),Yl);Qg(EjT4=+W", &
        "w$[^wju*LvY6]??yYn7/Ex*XlqCuZ4]BN(^8GL#xkgqHI/y*8dOufUAPZDip:/P?@:_Z9;_cdCTI>F+0iR_/^,?kCz)Li4F^_^<KcPY0Y)lp+2hQO(*wS5"]

    character(len=118), parameter :: BLOB_ROWS_2(100) = [character(len=118) :: &
        "O]gyvLfD@ZdJMm)%w+;?ISH4/<,Pk_oqG=?lN11nZ>Ni5+TkGq>D1zg`]eLlhon`T>9+Z51YR*-[jFBc]XFu;*oDjs%%9lxA]J*10gXz_b5_>[4P>vLo09", &
        "hsju4.:N$O`?u._iho?4AX^uK:P>bMIai8a^eiUkJHwe:xL=gV?y+>KW64njYz$+P>Wi5mGD0LWFq9kq.1eP@iq8LkCGD(.]DJ<0Rq1S-r7K<m5nXDO@wg", &
        "sIunRCtUalf<c[2fcUn*uMCc<AR(@[q9-m2i@D8+JL:kJ_A,L?Dtj0Ho8#JWTd:(Yd120%eRe(u6*wb:M1_a7B1(_]OqucjrX<;27bSeqWWqp>t1d.$Zd@", &
        "L7Bx>L9^ejeEN:Nd@Bd@atkJ[eUv^D:*W[FREoN7_fa`nu>dWd`V;0)F+lA%,9CFGt1qBh=Oit24(-kH?c,hbAVF:S8+DvJhUuTlFDzc,RF5T]w+<Ccy%j", &
        "1N/I7n0Apbmctwho8^x#k)Pv6$8Zo2V/r=%HD6XOIt5*,@_#i^NSI>6rPihr=mgEx8yk#^RN^hilCo$6#y?tg*bBE7G>Aud%<y8m>`dfwf@k#R]=wpe[qF", &
        "T4Fd6[.>8cCWAZ@@-)y6e?Z:`ETic#X[u06Xuk-^?,lW1T,9*/2N(avZsM+cx8;U4j7j+H3bW(:0UJ[?ize5GDFCfdPpa<O5#[t5,mM#to)[U7XPoR%^T.", &
        "kg6E$Os6_082p(^0P(khmL%Um;I2EI1;(6a.P*R<Sf$+PE>`P>Nud8*]tM3AE1U46SMs(#pR=ibEJjaTUQ%LvB;FnvT[vv)x#63q(5(:*VobogAjdv5qv)", &
        "7HwVY0ObGTzDCGZH`cZX4xQe_fCXcA*WYVit/NVk($5V*R8DuXq<+EHoU=l_SNP)mp5J/681lRdPS`F*hd@x<,8=wVDT:k9XX+Iv<$VRoV/c#N1k`iVb/t", &
        "g<HjObR]=42Q2G8R$Gw<9FRq_C7(bcr2Bv]t+]8/*5nJzF2A=X;<HLw#U8dZL,AEqa*b,s#_V#rk:e_3Dx;`8_@k0`@<$zDfOT:F[rtd>B<Fn16j9LI2QM", &
        "To+D+ZfrfBWY6A,?AQSLq_#WwSkWRYNp9kXpXiU0[^X1=^dIE`.N:O.#dtk%q^oi(>A0fX_6Y2mrAiMKc`owf73/vsJs+WI)J($aOUTi<^HBW7G,eW>6gc", &
        "RtqH/te$rBu*?cIp^:1$JxCJZdcNsf@C1F7.`,.;/qSVQ%uQo%I2jnySg:)G/M.W#%W=g#41N??u11Uuv%hIkSRty(-2[M@KOJje;VLxi:yik=D8ijMSpE", &
        "pK=%WBu]CQ9mJszI1^oY4u+@i05f-F(1RtYg^u7<C%TH%*U<^XwS]XI>H/T(cdsH[D<(kv.C;$#_eV_?i45.`EgdZBsVE(K60PR31+e5R.AbVoNL_v<ZWB", &
        "$(pB=d$XOe6a1[`W,%d.S<_O:^w,3`W,36(Dc]uS-50x?v5hRlF3X.mpH`R28Q?pe8fHRT/*h)He_Z8^R0r]DZ^G1JcBEFYlG$anq:kU+=BQIY:iuGg<6Q", &
        "2tXzxQ<LJgj;bmeNCoiRW1rGclkN)G_AD4dA7]>aXJbPJgg5)41_Va%iI742U,6pc*@lv8zmhaxJ=ZO,fx/x>^wCu;J^_)=d7o(VK+^6e`+aOX#p#FdXV]", &
        ")PuqTwQhg(3/G;MJZ[;a*fX0Fprm03iU;J3sjU1X`kOTHcj]st<3z^:>iYll1:9qtN+<NJT+-[Xm.x1k@gZtt,5D^u-R]pmL8hXjogiqRLvZuTYpGDy(+;", &
        "uE1#F%QjEA5xw2aKmeyk<9_ef#dl^=[kl)kD:=b`2,;@xE@,.27$3][#d#`^n$ZNk5CrptnG8Wp8A*F)dWDD]^XgPgiYv,E@eLG[N2k(*hh-YQ=YB;iGzv", &
        "q*Gz[[x<A-*jNnxfQ6C:F-+t*s6<(>uQbrq7;(`Houa@QzQD:o-P]/A#+5>-xU(M4HzF,HH4BRi,oipR=k[q_c/P7`1El/0jkMOOV]pX`7fLsb]U,a)ATZ", &
        "464T8B^.HmPi(h6*Ep`+YgBi#c-tgTTV?xjpEM/;+[[/d#,xtT<GY)n2H]Wd=(/O4fusNw0>[i5*Y0Wdriab8teDZLWHEtPLo[aV>,hrrEWC>4ZNM.$ZY/", &
        "0,#x2[^alBkW]K+40]fy29u$=o?f<;(x9AwPRXpoF/jQ7T8>yM7VFebZ:tQ#cu43E4E)/>bjqg$](<WC7srs9Po>1nx6C30it_df^V3takLx/G/gD8I^14", &
        "4V6T`]DL1V<x/EE_C:pZmDW$KL_5+)LXC=6xB[bJ9=,vlNZyu>.aJfUqk:$?Nbi9gDx/IuAxWpi/^/F.cG^-0aBLD.mq0(+Wsj#wxZ=tQ>43J@H<G?@XZt", &
        "G#M2=p_%^MQ##w4ZfG[d+-BOtEMfW@@21fnqvzyLXCTE+/K??s32%3r=@u8uewD^AsmUloQ@7v63[)THD.,%L?1JZ;Lv:*`a@`$JBK#aK#dBY4gs/t3ON)", &
        "j9R/QYY>W3WSsdMlZ^zEJz[3oa]O#T>vDYl9>A?wS_t66,gmwd2sWJ:gPa<=J4F;Zh3$gz3o)6h2j<$S@*dFaO1wLwTZYW$d3QCyKqhE/;vZ7>e`n0s`oR", &
        "l_b=)j`gnl8MfpwT(^KqXAn>CjNxvnh^zzazxU67,Te:-;;=h-)=QxI9>)9+Uhgk,@Kjt$v[Sgln:x:M>sf62?(GCM9>#WthCo>OGN>j15S8%4jt/H^u-]", &
        "n_OJ9^>9yHZDO2U.vb(r._;h2%UPQwFFSD%omBrF(RcJo6JLa*28Qs+<6rIkk(H)wGH$B*,HU.nnJ[-di?DXXymE.c4V<=A@er>m,SgHO(AgTH2>`J#,p#", &
        "Plc%R:NFKRig%#lo98R>Q=UY5zY[7RhJ<Hhu[4N_Uck)cDNpDywW(@^8jz67vN*1<-LfvXGj=c[3I<.p]AeIy#9+snKCL3Z3iUs7^d9u>wV5H<5k4_SNA#", &
        "nm4v$vdzob4-B)H*TOGU*^e_hEh4^5D_viid`k0gidg)a-jZS0RHkjzGM9B<8Z4(*t-Jd?ujN#W3_Y]+%GBEtr5DD_c_K7$mt+Ricb*eKrNa[Mgq<CGv6_", &
        "jGD7#9T1VIsD[QJOuD-y1@P,%lXq6^XRVubCA>c@Dg/<_SDqRipFh_y*gR[NtHm8AG%W7[vTs[NG<u5)ffQg,c#m95gk;UADt6OZ^>F=+7iQ->VQA_?=VE", &
        "T3.I.2Z`CD:X)/fG4n6wd0=.<@Y;rQtrrp(IhF11nqW22^dPN2)SCXWvUgz2URpne+6m]p/adJ2rAaMndeSLZ0lR@Ua-dM=c^jA.Odj0=PB6Re<n:.sNW,", &
        "^%tR[et*GGkW@d[NZRNdbO1<J=,gnqcLZ(cL6D:Xe(JI[bOYu^4jlD]f[o/mx(K+mT;4<Bw:C%?V3Ry65Q%_>2#`/fT+QgXvHujtj5-84oh5^]`izCt,G%", &
        "14T>c?tT/<w5)vWeFW_n8Bl0Gp8XKDzEfZ`y?1Ly`6h1[1/xv2m`V%-Kya9c@C,/<2_bV/-1[XWj10ShzyRR]oKoVaW]]X#>nW/d)$q%CC-c+XUe#NLh;(", &
        "_rHc?.5#T?7#.JYY9K***IJ5x*btA9q;%aGskCJ=0Ol[;Q:_#.+SqTD%z)3$LeKas4FH`lYgW$/lg<T=N$57:PZtYr]O(NVgUbA_KwLl%v*S:9*;IJ(70x", &
        "_Mkc9C<r@biRkW9w#Q_ER3K%znvcimK*OwhvE@^atW.b;WKpCfw9mY)Vi]I)PAulAI(e:g<cO`A:p_x%ymCz(rWCbk)L88COyEjVPRX^.5E8fIpmXJ6C,-", &
        "N4:t^>;/dRBZ`t6zIQo=7Lt?aO*qq*[guQSNeInqyQmE+ZCO?Z.@b;eG=kx)_hyy.uTI];SLpG(HIzU_Ix<$jpob,Rrt-Hr-iEEg>Jiu88g6Ifoyf9T>$z", &
        "A9w/2hG3#W]UHK#j?oxA@IgZRY1@c$458Bg^/Rie9>cnm/ayH%yF?yN;jHD6<)`hSlnZ3sA?aV`?T,s)43x_jY,F$Vf$]R)D0j6pnuw1;5g<w<[_Y06vT2", &
        "GUdn]A6Eh@RQw$OXLy3%p`SHY:^VFpN_al:VujtS`V_=<``[d*V.$:7p_.mGzNEt;Vo%[da5B?-AZ_bQ>XVE>tkS2/DzEm]6:VKX0$ksaYh^DKl$@$v6B<", &
        "q.o*W$,:8#Dd-a11i/*;:[W=q@p7qK;(M@`+#S^@fM[b4)Ig*O=F,?/no+jTk=bTVS[>-I.y*F[/>M;/$O`AA=NVuEULwV]/txe/nfRmXVrX+S/qTPh0)-", &
        "C#lQf6nRzG7;6%O`pA(x.TTHnmBAPkh<t[+@aI,BMxNCcKL<@Hrf)ofaaqv[mrDp(]lXdy=4l/$*Yp%8c7W8a,iVQ(V):.:vi#ggn?T2$+vK<ywft_MDOf", &
        "#]Z:Sx(bghuoKA:a2E=sN6^S@o]F@*yJoeQ?4KZ)(EScdbqe2,[V74-GKXRT^MwxQcbVB(9+;?$V3U1W4vz_VwL9W>[22T;mOW)9tR_t1ojqNZ]0v+?zrx", &
        "m2/8iNHGN>O7dNZ1S:Wdd)]2)F<5Jcs2n/R52dQ6<>n?(2m08$lT)rm%ZbuYF4ipS^qRz=i[EW6y<4oFCFdvz+1[jp^<x1yrLbxA]-2?*rloZXmT**^kZ2", &
        "jxD90p^?(toJg).4YrPi^P_.d/8/@oCBh$]z>2AhBb/*ZycO7kZP2_]Y67(?AkS0MT^3TyfoivmRg:D3cW?GVTlCeirp;q>C^S]Nl=-7)GU[;0Ya<@-$QE", &
        "JS_aH273c%P]-@,<$s;`p[ExfV4@*F.--TA$xC$Sw-C-,V/c=L0k.vgugJL>dS+B3TJ,]*0V0^`=]M^$XQATz:@5Ea26F[MNYY=>%YD6B1^PlOP2?nzuqJ", &
        "=<++=50^VLY5d##@A1SG-wFFkxFX2pFBUha?dq+<(isDFolh=Be5;#=dq`-(=L*Ul*Qh9feJ=*9`4,*.#G@0eV=jAFPk)O;,)E%PSw/8f4)7-b;/4u>][o", &
        "5wT?v>,@*9rmCr=%Rg.BYPIN5qK^gfR./<vMz@aa:2vPS5ws1-?y#GIM2xeJf@UjHQVnXVkv/R-6Q`OJ)E7$(0G9K[7L`,N^cyL1HD<`DdRGu2zv]r6(s(", &
        "=_:HTyT:I:`U*)j^4dbSUbB7$pF<2*7:TT<x91yoKpgWWW;PGhq#L*D5=0=8HZ0z;uf3GXp3t^0t)0#mn(`1aloO;*7n,Fsxdw<VRD-4^1SH9ACX_NiN,d", &
        "`OG<(mygdce;=JE1<4JkD4V.3iV?Ur2-q>Wi6#na.1%I3=@I9j8cd)q8p7s>V(rK/;R/QaWytlrujsZyv8I/kz>4=gre)-g<*WD%;E_=93P:#s?pd4wB0p", &
        "URm3]T-QYC%+eD7->+d5(0s905#ERp)?W_V9f#IelJ%PM5+F7DEq*u.KYTM4XvyHo1bqfNWxUHx846r3(+6e3a:HGX>Wb1dgU4Y60MsV8OJkzD4sj)I1PN", &
        "::`*9.y3QYrd060y^9J2`/0rNTZ%yPzyO2Dd-n6]U8mQXh)P*<:S/JE3zTwXRVE[R8FA4vCFRySUFPh3W$5<NL@/R/oE=_XV1Em?#c.y5lcTQjZAbLpdFg", &
        "DZZl1udwMn[>GX[oGp/)p%@_WheUtmsyL%6*QlZ<U#AD5kkqN+1b$e2rj[j:H4)3A2L).<_SKN.F];QIEXx<V:hTxFPyTrecMY((@#nV.(bzw:n<yWvX,R", &
        "<228XZQvG(,d*ALa2Wh6;,-E[*tCQhSfY3j`qQeFuNqUvs7_NH>M7Vw*.JdY#P@85QTaRfk4`fq2+:0a*<fiw2I)mgn?_wNYF2WOHSY1Gy$k8:<Mx#y13Y", &
        "qI?`N-ddT_-efF^.Cz<3YpDBE$oC7^)XNpBkpS5pH?tnh9^)g4aU^3RjDHnF-nXI1rglvQK_$Dmk=?(.b(-+WSxwuUY]m$YLaRe5D.gWHz,;FnO_jA`umy", &
        "#r(v8dd[Rti8WDa:$l@$.6pjD:/k]h</M;tS%/o[;4=Jdr<)Cgb45GPow*9:jd-,+(7:(pTa)rDjH(2]BgA(:8Z9JbIxv0MYxd5d]l3?D+st8;SD*j5qRb", &
        "?r2GSJNUL>[t6=512c_KBJ)mXkk(Ht)4vEsRm0FOrUcn5%f^)eiaheI<I@Fib<>]N>2NNJl_fM9Xb@WK;L2aFWj,%/85$/`H$1hiU++U%<*7U?IU[mQ*4Y", &
        "Bz)f?igSp#j^Ts-tTv4F1*.W-Qo,A8ILRKX6C($RgOlinPw0l3_=?XDpp*_QifiAjDKA@hDlqTj>ePq2[cE_pgEgLeHIp>,ApVPf`PC7_HRgujULFCq*]I", &
        "_h2_b6DWLsB@;7bi]$:dVT%0cL7ipAAP54a-2a1<[d*0r/?^i(7BC8ofs_okRi`xd25XgQ_5qbjag<Nt0X%?SnFTCjk]Kq#)Ru,->acfmqx;4A^B]rZ*e4", &
        "x4^@Qjb]Hs$22MIfam;L`X]gTF:JYs;Y40i6Vw01Wlq=iAd_i3lW:9TR[l$hB1uhHS*[h(=V?SDfl.JdmGQXLyRw1vwt29Vz?9$(G-OGA7l%wQZcG<W;SS", &
        "8f%nF-Av,-fz4WRK0j:COMBo:>+r65+Q+a8Xp0#sBwY=MCYMhlHTn_8bWa#L^w[$A[QJIWBKdmIGH]PmPXSBH<%.FlW1dr,NUR?7d)dKP1cldeVPbx30e8", &
        "%u?:[zdTz-)J4l1pDIdW,6Y1ZUn(VnE`g0$Oz:C:v3Y>_2`KE:]NhXmJ-njyf.YkT>0(7J-4_DuR$OI5G6^Z]=cenYG[*--^wj@^%(_j*Q]nPeK+VqtCm9", &
        "qndOiaVRZ3PX9L6SIi5G5hP^8@,1N3-eIBrUIF$>cBc7ZW:LEpRfj31BF`K5:f0w0@?,chJW6T?D8CULXJQ1FUx$9o0j;1NQ4?=vCyOdL8I=<*I/RTAV-5", &
        "5VI/3CaVD+_Z%65sA*MT.O[L,h42GA[66SrgDC*M<fFGw7Waz82pc$0K,vy)fglt_l+RlRV)S;e+ETI3J@u6di0zdo3vx+jCSw1u?:xye]v+0>PT%g@.3C", &
        "w>R+s#V<nN6+W*Qj(`ia/Haa_$TOtoLU^g<(]pK*+ehTKE+yPE``G*XujSt?b+P_O-TM]0th`0G5JNr-Nyl]CmQ#u)6pZkq6r#f469m.r:Fd4F_<dgW3$b", &
        "5:[QVqOTX8Ynl8W%,WRkm$LOWD1S3cRp-W;_HRv4qEAehA^gmP.Rs8V3[qiu5EZb#V?s;i7y=3=eHfG$u]QNJ?xgu+/cDVQPs$OJsP1XHF/cwAuCx,y.WT", &
        "jC>@<t(94Bx6<RMdFJ_hsE<_NLw])JBgL5i@hbT5XG;K4q#8lgBhOqpTH;ECwwEkxHsbcb8S%hb+i.:z]=tLY*LA3(w[OkQ271<^cS=Ww`u*.,`(9eGS2R", &
        "FtxI,W%Glo.Yq0<k6U2dr2Uz$(I]+./5J`5*U??RN:aGI9U4Jfs3(iL>U*132QgkdE;j?(<6f8gjgyA:v0@Gp)03NerVHt/xEJ.Fg@r2DY@;O_X/7S`c+(", &
        "EXD[*jBVbEel+IbMjB<R:^Wm,?4p#JH`,mum_qbfHKg:ABE51v@0IbNGZi)8g;zWc/O$2HS2r(LwY.-J]0s,DG=jbl@O,0*1#X]Fb/R.5q(5@%`t/^;EYY", &
        "Rzt/^B$c8_#dh@S+goRh<$%*-af,#UL>w*9]a5I7>Tr@$TVSEI<2++d*zQ?6yzrGt/9P6c,d>ao^8.=.)^Ouxfvi5wUSe`#28j^]SCyIPF7z+$J#jdcx,_", &
        "9vXf8:>.z*8SB>kTA87G0)k8m+LU]V[G1SS/8cea/_c8gJ%syF5myBj>O#._WBS8g(:*0a7@js7>1?s+6^qKZhc]]7/2f<MsXopc@7)B?n,f@Wg?)$:d0i", &
        "v(PVQM83?LZ[]s:8[bfEOx]xNTVQUe]P.ntZ;PH]Q@Cc,uX@U$5%652xW66C[hY`iHR41A5;ihh9cu9mf_(GK;02-hBF6L%nEVC6QICH>0e1:X:_8E)nw(", &
        "O_>^rj*1BReAg)vD/*G?_7`ArZpYd$GlL4+C0R3)QNe[,6sf@/iku?A5#3U/N;-DjkgX[p+ZE%:Pj92JGfjS5+Il,/OqD1N1y2MLdIqM5R*XH51DM]jt5u", &
        "a?7Yi>R%mI/Myt0AayionO90R+_448;>JN]@>1CVo1SpyYu]LU>GZ1=3I*h)=BP$34k-o`vcXLO>=f%dDvxj-JrnV4fgV2F^w;9<BrS+##=.2%698]<Fa=", &
        ",iWQ-.Zto)gp^09e/8LBe5BGtA#_He%3WY>>vkIJ07kC(HA8vE;<L#p8Z-p^^Vo3G8I)gEK0za3_9k:MM(CTLzx:#i1f.(*t[sPCf(3d*x+8UT3mAcRfz$", &
        "naZLRLNZMQ>IOhqugY)W%lorA,xJ27YPanAO>V0G]qXh>sfOxdO4KqlROUHmQt(QV6Jr6:4a5fbmLQXP+z<h]vETLXO[5Kr>d`MB0Y7TE4i%EupYwm0e5^", &
        "mX8yQ#Q:92OV:?wv$p]n_re>/P5$Kegq_<D3X:iSDNQa;hcL8YIx,_AYDIMW:i-pi5[,<Rh@tC`+f4i<EN1pO]=gyzl[%s`<75^Dt2PIU7f+tu2MU(a_g=", &
        "D17]bPmIM%j64]1VxqmT]uIKf]),]9KtG7:y)S(v8+]rDJTjIfd[5#k8l1%I$z,W<8L7FhK@Xoo/E8KZ9Gm0gLpuxPN/25TA8/A7C.fuVCuR0mF<Oop<+G", &
        "m=`4Fr+=KsLS2A,f,e/^[9y$Kxa]46x/Z%@)YJ1F/1p`Y1Sf(w(BdWFk7SH9O1b#)f6Y,3?(N[_g0oJ<JgxBWJETK`:0W:<q(Nt#-,dxoI[sN-MR7t>LPY", &
        "b1=kFs)g+q31vI^)^#Pj4xSm]K`A(>wj5VihAOc.OjQe/A6C/n2+J0a332KJRyjgJaN7CSDtxTeKrnXw/$=%mY^:mG3.r2cp$Q#k-WD^eSTx;CP1+GfR+[", &
        "cZF5<t9B*MEC$=nSuK5BGB`l3,r.CM01UaC1s%7f%JyeNs.0G<r8c#$u:$[RJ7<r9%@EbvI(*D/k+3_KcSGHLtBbyE5a@TrnmJ#vk:f;(W52n9I_-#IJ07", &
        "GWRmNopLbSALw4`brjOZS@,O:`DSQ6TfL,qe`*cIUL9av?N$OC(R6GoBG=.8oVF<1WI2Vwm,(te24e0AlyDY]c*+xUeUOcFJq]*S3gdOMkL@L+sxd_*0Z`", &
        "wdsz[.DeJK.EDii%znsb%t4SEUNXn%KSyf_zwfTkxhh-MmM+[GN%%=Wp?AyoS9VfFQ3v0%/`hA]fFm)AGWo^FD)@1=.D`mOYb%su399[1R`;3=9OrGZ%.d", &
        "FH.wnUs;tLa%%@*=MfGY^dVW+w9LoZM9$v0P:;TRJ`YH6@u,H;k*hp7nBULN?hY:7USI.Q1^n`wy*Tr2v,r/ZGrQU>XRtEr0U5E%8s%0Im/o;Wq+,J=dVn", &
        "y^qcRc>hnM%j6MUr-kg)M?)j9drx0;^k0/6S]u/T6R-Kb8n28KY_5Anr>o$ND/JQdFBb<*iujE?5BgwPfalP6qGIvM%F)0gG.N*Tht#=O)@4LS=w32/9h#", &
        "<)W^0N/*1cU[3L#u^lPJ)-ya=S[ho.J6VDCbc1r*LcA_VA7AnsZelb`F=dDpK:=)@m(KjV$WH=;qaZMDNxJIRvVJ?X16L[sim4e?Ss1op#sfKo$`gPm61c", &
        "O]`INM?CiKtB?A?/RFFu,nD0IA7vW+S=eZi-1p8%ZZPkTuhYK)HI]BhE7I^6I`om`1t*D0t57VwAC7#zW;_vUfM?#ha:._>BJRp)[?accJZR2_tVvjhsNP", &
        "F5FRd7vN6E`L.8+Uk%+]mcq19xWA2J[.)%6XVD;9Bn=V@*K^l[=0zNaT8l*Fk04.i)st,1BDIsDE+,.aPjbDFqwNijB46n1^]xM$k]VlJ3qhCQs2Cp5BdV", &
        "EE4Ikg`mn40NC$(1>1KnIJ#L8<MI^C:e#@n<ck@Wa0^#Ar1BA1fA02wu9+<g[hpj#K`v+.HTyshG#IEx8W1e4_DEfAEtLR7hZkn3r[iWG)L$ayTQ`fO?kX", &
        "CpT<ReL,`%r:>IzaD[ErU;qc1)zxXeS*kwd9QZgsm%;VynctT>Hx]9vuQ_PzVajob/4.roL`dvq3n@t8XquVav$5R=FnOr*%S-[j/KSbEw*T`1%O*Kx$5k", &
        "ELyV=BnCM;WYVPaT^m)f>qFC;)xDVxV2_Ui$P*kQTM1#hV,zcvPXN^O,oA0/H*QGa.BFcn8:x1osUE6ws)vU2fx?t`;7j1wZF7*t@/8R=:Q:xmAebgVl=P", &
        "Dks85nrq#EACTBF#z;Gbu2eH[nMa66=XBkHW;Pk7g?,r<VQt:T/_33fQIv]4A1#<xs$=,V_iP.EwaETD,.?7.lHM_^H`?yTf=YoVADDFC)-?YDfx>Wa`f8", &
        "kCAyUvJu5/goLD_7*WZ.=`/e@c:-0x1X.]<f-7ABCMvIk,#%J3_CfB`RgMRw[(JUrEFb(;vR#e.w`ZlYFG_OosVEonhOHF7j01z=/gt^g>++U?S*v+QV(Q", &
        "ycWRtAClfYV>/;_l%cK]oG7DNG`r8N<I_;xsclW3dE=>AQE=E-KM(XMeWdIRWw*$L=)zj(ncpW0i,*k[cpBc_l[;0pkCRS8F[ZU3RR/5*Rj0T]NJ.dghq2", &
        "keT?r%53`;Ym::h^kVq0__5WrbDU/,<S$l=cH`lISRD7^N.E#edzYEN:h`Db>jM*hkp?9tKLqdHOI:O9Rzi5<Ke`imL1sC1wQE6NMHYc*L+wP,k]ut`*Ce", &
        "ald5c0C)RbWy/]/r^X)JZ.UJee:flMR^O6bebJJL%aLn[x$hm>7AogvMDQ-_Z4VnR_OxeBpP5Gm@79Y,d73YDu4f#u5fTI%$P)(3kIr3nT@=6O;(7=27J[", &
        "/J+`NzfL6n>j;kPxZvR54wO5/J)bTWaR_:+w`03VO`4>I9fMCdM4OQ=@I2Y2P<]ww55R5nv_US-kuC:Z3u^n_a=jTusbnsuoVwLRbSE7AQ*rE>$6wpO-J(", &
        "E],Lm]gBfDm9DT`aEmt,F+C7%qNx/4_509rAidy]:3JU9<@:-=A(4dgeJNkZwd++1XJLWlK)VSQitwFevRxSFp]]v`0LVDR[zZ`[DO:-Q*Vdg:)Yk3l8hJ", &
        "+5C`F.+:YxvBY5FbMI0i^6a4TCTfT#,<g-=0?>v#W$<1=bD]Zm4bifAxV5qF]QM>4dq4eQ)?qB4A[<nOS),37sXjWB#HR#afA;O@@V+NVhPhgq0G#r-ZOT", &
        "V`uk5klog<]F,dstu;[C3Kf:Jww+#C%z5p@8sIr$w_PQGK]+L;;,L47tfyATQCKt$l=DhRA;0VXs6UXvJFVn/v$d7/0m.-ZpttgK-OS:#M#Fg#m$Jb9Z@A", &
        "]GOKK5=(BaaAV@=tap=fKzQIx_B>xeK+NdQlkWZ_sE-?e@<GkD>HBRh<Sx_MUqjiyw/,XG6izAxaj*IgS78(Q;.%59`QLi664D_fs8ra`3`Fg;0UBMn[]A", &
        "R5Gz8gvB`s?C,v14$ajg;/dCl+g6HI)UHxe:F=[VA=)rPho0BL[)BBrEXRJ%+b/n:9x$BMmJquV2jn@yzbYT%c(7do4Y]@n?^8s2vY=vz+ehB$GCidX97k", &
        "y-p]7+zXce0Op9R4Kyvu]b_NHllZqb][G5gq86]sgu9OZQ-5KZmT/i6yTzTHeE22clOsG^^a)m6OFv1q^5.Ze79_Z4wM-o0;*qu[dtNsd9lxY#x-:wUDro", &
        "V%LD1gr+wX`81>bEO<)HY/fI4O8(*i3SGd$S2WYrOUA<$L7PYn4ggX?3gh/CQnR4.ulM-[7Zvj?1-1)?$?St[b009[r1z:e>UsNTEhv_4LM-MHtDMYVoef", &
        "QYz-F_>N6-5k,P=GcxcjmXPPSS+wt8H:?*%?5sXt_NuwUwGjw1>5WddC%JOl*66p6Uy>+buXt:pF]mIXGhb3Pm*bU:v=r5nZWGO2^rLJGtVX5G<BoE`Ni#"]

    character(len=118), parameter :: BLOB_ROWS_3(86) = [character(len=118) :: &
        "s=/0V_<FlmEU6R.TGgC?FP,lEx-@/uh)uCznghomY4A$XTpA00PT7kfiWnrf4)gsd(X_Tt%,)T:;adBI<`Sa;3kp+f%D(ssERcR4aoU/ua%pdUO0B4kiA[", &
        "+Uv%PqNW6%TlVeabeR=fG:i,Y_o^^=S-$]van5.nBP:PAFDhk4MB-;uITjc3uxR?hkEsl;dTVFcwCZV#)<Z.e-zFu$+sEw3k*;uNu.DIk(CUq3%+g3AD4T", &
        "dU[.l:]MG<2>@0Z+Ob@iZG%$l=2.95vv$yHXQ1]PJj<)V9LeqFzdbyErMtq4iOSrjTh.-vQOs*ler=-a]2wTGg>p:T>NHTIyNlsgBpyz<[E_e]p0b6sxU%", &
        "(vmfKHx*=4zs1,e]A;8HED,*UxMBi]+k$HG]VR22aG%4:x+Ij9atkIO7tNx`n;0Ux.c1^LeK=6)=p/^q*hX:[b@S[4#r2,<,C]<+=[oee7LC+sxDLa>Q;6", &
        "zsKhTmD=:XxbYfFx;%3[lsint)AffUrSPi?=jmj%iM>#qgJcXH;4XQ]C3Z%+j:2-LF+Wpb>GSYSI*PQiFsW$x=hS,fJtko$DCEi`/ZLnjVU`Xm>2[U%s*z", &
        "tP>5`7Vvs=g[;q9BA:fXu/:v2pl1D9$T0hH:uXu==j3)GD.4gEL%LGvWBnS=iC%rimahD2J@K.I#p5[g^X938Z9ds$NsY7?;p<DxVYh7r`oJEHr4F(]cQ[", &
        "8x30Qlf2ZqH)4PY#RFQ_G._h46u-=Ef6/H)Js7V3e,7n>v1rmfPb0NkG@_ioUB3mqFi0Hx$53/^H6.ai<8(mmshYEP#emvSSKv9Z=Xi^EG@lWshYi7(=Qq", &
        "$:[XqaC=+X^x^+Yo2[00=O4VH02,)BAY/bsp2?COse=WJ#CT`:)c4$SknuUnD_Wq)Q?[*Qs1CXe8Hpg0]sdHXKutJSQ)Zp-Dga_[6jHSpZ%U4;Ho[>vfKd", &
        "-s^^Q1LEA,QjhfsfQW-FvLH/Pr`>-++g0KzKmF4yb/UB)j?7.fQI4m?5Pc=bKe_7h*DOgb,/1#`vWqEJ+7W3m+[1Yqbbtj@bIMRE@Tk[PjPWq)fN5Q)8Ia", &
        "CoDO-T*x^Do.MAyVk)mHuC_@`?tVF1Vix+6PRCJN[<_t40])%QBLSlgHkRX(hH9Umuf=?FS$]2QIyJ2`,$)5,@-<V*?ob0HpKi+B`<at5C)f?S7JMYN9EO", &
        "=E-zc2vSxKg;grCPn%mKCL<flpvBYSiafuQZCIgbU<:(Pok/U3ONbLyQPGCZZ-gPM0637dA+)E^3WL1XUy8FHmkW+FRCa%_0n#GE+/Dz(_oEbMuR/]5WSt", &
        "z;O-r>8CaLUnavvd@>f-Qp;n]nRLTzHu>vkC1sAvDjU?$9R%d%`nn^wT=E*Hj]`kIbO4F+zo$zFDjV.%fI:@cUHPq@ZCV;DUuE2PEjq;N9-,yC(%v)]nC2", &
        "6s9uVdFn/4BmNr2:5F<G;vefeK<OgoSB+P1uv7rl%JXd:9k=`8@?cY;uW=av+a[?Fm8C8Q)be%T#oY>7.-7`KUSMrP2MzbQP^uW>m,2V4XmVsMreW>asNo", &
        "[SXiR_p%E2<_C*Y-o[PR02]rTgR3>jR=5n_:1h6WapYp;3SK%@`DPZ:CSR:EZCTHTRFYc`]U)7LLw@R1tQLINH(UHtb+_OA;e=u@rrt^ToqJa:Nja`PiZd", &
        "*VoFT3sU9=7>7^hc+nl;xs`H9kRn*.rhkT]7lxck?kt6SfBc?GDVqoF<.%p5)*5XcyWWofeu/sSjYJS=pi+Wb$<CB_[eE6*l:Brrjy-CH?+QJ+1O4S5vgc", &
        ".60[[(x_8MXs58HgzTw%*8w7>R@tZ)fiE%aD7b,?>.YP$oe:$Z4Z4jf4Lq>m.eV3KEi#Bt>SfA5w6ys,C<08KR+aA;ol$mWFla>G=($=fBUcv]eG.Uf_yk", &
        "s=nZg2kOTYj]AnNop7Uj?XddG/*[z-_o_hn7373PSHO<bwl+<9]J:;0>41<1(,9aO3bRCvTY<S<^Ej$RWUqoA%$niQOJieP%>ERJB%XkaLtIs1]KvNi(_Y", &
        "3neu#FwCht(wzp0YG6k>#zID?HJ(8Pr%cF6X_DrpZyD8CxOcm*Y%u04oM.d9nxlH:%*gM2;dM#fFQ(3l1sT4:J@i(;knX+ByCe+dcd9GUWB08bhG+I9Dvh", &
        "_,8:2$ViJUQ5+IdfQ,ouSGq.x=dDn1_06ylX1G63PGMq@h(ey+Hj]o0Z48?F?*[*zZ,AaY^b$0i;GM)(mdp8ATjvt-7-i9URLdaznt.39g_p+S2GMN,@+B", &
        "XH=JW2vvgYNz,r1/iNT>VX;/oVA)PZpB@p%e2h?pje`)87:`O.[IQ@`Ew0<t-2oT8:6+Pa)wf)4,bX(o(kT2S?sz@#gt@*o`=Zv$$kO=M=+K<8:7oD`S)y", &
        "pxqLuD^DI*[5[1>9A%]ce@p,oU`/@mRQCAmZ/EyvO4u/zOjPafq<T(Zw@P<[>x0[;Zf5F%)[q#D0*J[[Sz[yEI_L--FVNk9PGJnDD(*ozE>mYj2VTx<;(5", &
        "p`_PwFrUrlFGgP.s#R-Py9*6Cva4xRq;S6U=rs0$6dwM@3owiIpyR9HFs10xD:*?XFkGQe$?:26>#tOXX_`-^94a3MF5m-AOt_:B*?9KhFak#s?lFXxh^5", &
        "PwpID@4vfpFW%2*>ki>T*,b<:aM7iIH,-WPMeVXNh<G+QDlN)hOC=q0+wOZ2CeB2@P_DjQ-u.Mq8l,t:nlrsTpGF-DPWaYQ/p@HFJcsHWCn1@=itzV4U=O", &
        "j)ZZf=f1<)lIwf02/]MD7*z3>h$4%4KSMx5L4tF.JSt.>xG/,OH?q-.A#]isWA^0y2=mIgpg,Z%L;$XJc:FMtYPzz];5<Us<Fq-tyohx-ovY;C+;]2eR%u", &
        "yjJjXdUHek^W/WCDgKF0t7_LAeLV[vwK)BCIhgFhIYINHsci,XBLzphcp+gntvDAXl1RT=m$O[E;I+DV9lINCMz,sL>SG%)+aTmN9m;h86qmEsw,g2R^^T", &
        ")BG)`4r1q=#fyt=Ua#E`++h#INRClKA+?m#%1%qW]N6@1hVfbZ1CipbYQ:=Dscs3HHOX2g5DG3h.$=FUUKEB<^a]Lo6ej+q*^$vWVDTW*UDo?fDG-E$6eQ", &
        "Mn==EZ@NW:o,;domu8:,?Fv]n]n7hA=jiTo8mNNlxJ.mQ,+HQ``j]aDVh%H0SGHOX2g3y[sG[2b+8)?dN*pBk0@cmiQv)C2i%Fh#A<`W+[?J2hod`[No*4", &
        "5Fbrk%fd.Jc*.2AmrjWI$urBYlE5.B?bOy?)IxhvjjyrD=8m;m*:vaAjr_z/%Ee/#FGi7(R[Gv2?796obScB>ur2VP[]=>$*HuWWH@]0021[9>w(>zo`@_", &
        "o*>h1hedN2>Z.TW-`Ado:Sm+$fw]U4/1JTW)FlvHE0HX1X?P;?op(TLc?4EqIN8P8]7]GUmeP1p=Y+vTj=,M/UY1+8Tbmvu4#`,-.^enoz2<]+U=(2pdp0", &
        "+.*i3>,k[a;WUN$i5px%j+spd]xMv?wuMQX7YNP?P-m,Z6JQD+eG3vIES,_7%)qn$hFCa9PatPj,MCp4QUm/QjT^0mS<2Ix:-uWxq$Cr_+Y$*-zMc>uhZf", &
        ">=/,?J;6c;rld]-tw)1NgSx-uoqH)1Dwob#KAN1VSENsB2S58$[jvwwfsGK`XP*cJ38hJJfE8pG7#HA`QZbrek5?06<Uk%,Z<92xv`*w9>LTMwdoHFob1w", &
        "B`1t):Med,qn.95]igZ`AQEbb8WAJ#tf<YB8`%sgh`kIq``_B^1UTeAiXIzMP,v(`oM50b8CM(+h]h-XuelF*pbmk$TyLsd-ee2oQT.6#rtU;%taK0v.cG", &
        "cD,lMa;YG@nrj<R-9CvH961OO-.w8I7;sMvN+z_k`5_+Pn*`GLtNRrdku(79Rh)NO<xswm0fneHF/VjhNqBxGa[p?IS80su>r+:k$9F`gixD9BztBdXy=5", &
        "NJ+f=PUc;MqLUS515VARg3--ok;NyT+Hb5+Epo.q4B__uXoE+brJ5jxS.ML,G<H_F8/.VT)rls-$Py<J_YIge18_,HrK#yX#IP1t#EA]].b9m(5Yy9(ppk", &
        "qNG6=rh7F^e#L32IKiAn4J5<g-:g4>nPVCOFNV=`/PqQW*8KOs>+%5kzd5NPIp#Tnd_u2bxBjPwCWF-=[BugwCO/w_<zVvbK$O9=Y,YUqE-GJBRcO:0wd7", &
        "*PN%wq`-j,9#j;4Dd/:Td`zjjK@K1j]P)AHPv_E9sf=wup_v3iR#CRv(<l5T_)06sd%(WH<Zr,DefOQkqmdUB-v0nd-YP=<U4AF#3N:U;(ieh7ux/Rw),z", &
        "D#;s4n@f`%*@V:qRLIsQ/Z[1_b7j5k:Ahqz)VNQNPDUHTwL==r>b9zD?v6sV>N.A,]2CV7JaBs0Tm,AAy(:oKrbXMC7X+(2Z%0gqL+_mv<c>oDbz-F5bmh", &
        "r$(IMo:huYp>,-i$iA+tt,psvZ^Cu_vcfz/zu,@f%V.T/m-aD8>ngutS3)P-h-9@$NIZH(9DV.0[xNRP=zYX+WVM,m%rey8FX4h<cn=TZn*00D;*=`Ep#o", &
        "?Dnx(bwi?gsACjgEp4Q;I0X=f[dMA)d*Sil`BAI+A/*JVS:L+/c8,is$4GJ,;C[:ltZuqrsMne*V2(5AqRK$QHGcW)$<h^uycp[g-pbMZzCygvk^1#Rq[2", &
        "O+MikXJfKB%y$N/Y?u9Zb-=T]B+dUe?sIDVIrO*@`[^oHq]9(rwhe;k=mivmk#rQ^$P,5WuDeiNl-dWjwJP.X56*Qnm)D@EP,X,1tZb.#tA:*GR,oh;9RM", &
        "#]tmPG/QaN;wr4>%[TrpaCm%I-ZW[(isC9A69$UT3,1<1E4bA.+8DfjICza+nN2DF6fZ]hjsPQ^SJ<$5qE->1/=[ZkCpK%Itnd4pQFSrJGKeNn4O%QSE>s", &
        "*95t1/I%`t[ooB$0GvVIz4]GnKtaf^h<J[9ex:N(5Hjv.P[)??=`Sz<s(v(;tt6:5zWri^JlFqky?_oQq(^8<Y.FstTp#u*+H]SFm9(<sNFF))7(UMGUr_", &
        "or38Y9<X^<3]Fb#HNz7+V%B3o)Z2@9fHVk<Zr4<m`HA=I_0YpX#Z65YpjlHWyyr5DD*j*$1sc$0LCla>7/,.b([?qSv90BM5]u$%)9fNrXPq8ThQU53Zcc", &
        "(GKeNn4O%QF+hjQn;VF9a9wO,)PH#NUc-5j]o-h^O8dG/C<M.^690eiUdBqr/Eh[T2>OA(zV)b+]PqSEW%iDNW[9O#:/Ru3900*]ynxM,nK4HaP+F5zw_$", &
        "3w_1E@54+lSx;RzyrhQAmfzaC<;qJ+AMevTpYf$Y<d=jJkHMGW;U7)OeI$<N*;#AbiAGa=Lxt*3:spn?$F7h^$S/XZC#-)#Ff,:E^pY#3Ge3u9H<%*f_[^", &
        "dFu%Pu/pZi9xd,X,<s<N5QNSzoB0)(oa[YIm?J;b9eoMFOLz8k8wlD6O.iss?=uv]wt4+F/jpM(QfEM$u]Z)]=5VJ95cOfXXC0;dq8Zk_]SBlEcy/,WA;i", &
        "Pd-UEYK)nEm#m_IkUr:j/Q26mwSW4F/oA<w*d$Y+g[hX$IKYIpTaW%our(*H=GEFK-khldJ-oc=5+c_%H?73J99TajOY7-)4*uR)2dg)Vs.oK*28f#/Jv3", &
        "rG-2rD]p4.iMKkp?LKvB^*@.,ke@#al<$A)@fOe_8t#qY,MELdy<MHZCQz8l=;(,N5Hjm2N(cN7R+U2.4uUXktBJIwZh7NgJb[pl$):z(OSUa1ENr*$Ni<", &
        "k$Rjc`LrY$8?+NloFBK,0(wZcr_-qyBpt4Fm,]I[@5m[fF(h%-<(7MP0+2lHdK1i*)lHbe>rlO]y+X:H9ZNN<uDU6N0kAEgE$T(mtLOCo@(p9kO8,,7PGc", &
        "LpmQ371p)Al@i;ZVa6<cT]R]]RGr^,IRQc:0J.D;P;l:2>VPb+5cGDV?-D0wJC(V9B0CUKme[`YOn#SP*lF(C2UZ:gKC<<9n:<u04,3cTO%6>c=S(SQGgi", &
        ">1EEvKljMG[U?$Cbg3Ar7*/Y7=2/459EbF[DR:mOMa0XqgKYcT$Ha=XTJsD_cC>)h%[4x*T4T*q4[%1C3,[Db;mtzcADK[M,F*BsNBrM,6gizVE/[Z+T,g", &
        "0D)(0=*cv^]<vx)HIet#DT8>v]m3B$f=/UFS9_S<6i5g-^INNb%EEgH5l$O$C%kk,3tW,+m-5-Ktv7+DQh$JcguNPU^8+VqKvsL=H_Igx(3?n@Z=kM]oRW", &
        "I3wzKS,j#BVzVv4D3G)L#Ou^CF5bZhza:/a)PhL/Y/@eg%hKbu,K4765J<Je2ICmd_S+LMJQ=vv,Q5MWi>#LE6kBNUr[6rp^98[?3OyaPP(<DoQ3BGM>Pw", &
        "ZmW;af*Ez9%Ss7XTh+aA/*+Rz[4/tkose#%c)`0Ml,TpfX7?>Z?5*cQ.=Ykk)cjL$t[unZDM7WBW*OiIPpb5o8pBk+*<n>m+MF#+:(r_O6=%tEf$h0?Y*b", &
        "^t-Q*b,r<A]#1:4OZ)(SH)E/1#q%)U4GiSIjb-:tb>,7.,X1VG,6#etO^-1@[[[Zl:y)iev-;@iDUve:/46p]]Q`AD*8WbBdS;f$fEvwkh9qD*McZJc,2l", &
        ".V>UoZ16i8fCo]FJ0rRK4w31aZeeasa[T-$,Z0F-uHw`8Iw*9rDVT+DkIsCOJcDlySWVHr$Q5//7bI5r+J48bhVO@yP$Y=pds#eGKVpj2Sf@Yl8P4J+6xb", &
        "(ODeA-:s:KU7s`RjUVE8b-Rc)B<D$Pk3^URKQ79>L[*[zp(<-(bq4E4#.c.gYW/W4Itr@f8geXJT9H$)q-5,aeN4;z;d>gx^y(etu;2Cep).#*Yd*goiwH", &
        "AC^IR2fuvMn9LWNU_m.m-/NwgZvejvq5cU<>W4^^Sj<dD?iWk;(BxAil:zY=R_Zg`O+bbb:j;_;O9@Xg.,Ye@$9E/#-wniAeOkEp)y_PpK*3`p2mFjElk$", &
        "5rX[3(Azz,?A)[Vufnud+=^p32YXBXfm)-@EGvY<=qAZ(a+i=*E<Wn$[4G[JQ([i.r>R]l)-JevxJ3o5lWq_1nR>S`+X<5jv<BsyMJy0jZ1$23YL4CC+^S", &
        "EAoVGL<kI[^oKWiJNRn=vN;1)yu/4lp=xc],#Kt>F(@_JmlNQFATOEF.]4qCwzyV<VX1W1txTYF+7m?(qEdel`Hppqcte,a8F`O/b0)]hR;T9H:s/x/mF.", &
        "sULLbKYl?tDizaa=NvKo0k)?,I]rp2<RKMp/=y-c-@?H-4iq9W>PLgbMOoEs`=wmpiz`Rq4B7%d%jXdES8/.%cibe2U?5[y_Q>CgZrwZZmePwkx3H2J,O.", &
        "d.;XH3f0.V5ecqvj.P,)vxV.Y;(/Atq;%u<HcC:#rADwx]PoQ4O3DNL=O;(8#1dqrOO54X>fsHOc;Mf#/6qV`di<3V_Ftu4+*@6H^J8C5;HucH_/n<y<,j", &
        "%hO%*9gyrVx^+5gNX]a`?GJSW4519XPb0QUr3fe[w$XwqUo@:#effwj72f;rTJ1fp[lSjXQWz;K5/WTZuQI<,27X3]Wl$4F^J-X:%x,xLmza>?f`z*6dd9", &
        "ZRq@*tq6<fqE60tSQFgu,U=N#.FB_ooKsZnh5,ZYOMpHn:5IW=;oqn#cvjA;>h=di4_JHCcUj;)i)3tX4..S^Dk-H<nl2V^ES+Qfm+q/tSH]3sMQIZ*v:t", &
        "*mw+fRdW+h@w+h%_fV)TL_(^cn.$(Yt@fO5;gf/[U2T00rw$P)i;6M@CC<<l]pt*`izi[;(+_$BbKs#(jT`qO,jc5NYQ0.YEdXx4`1Nlq(Xfhj$g9C(0h=", &
        "ZnY=S;w8)gSuO#Y)V4ZhWAcVs,vzq?DH^@hm$M/^.EK@eM$0qRlvl,yl6So^DNE<sS[sAuICt*MI)r$gVt*6%eezdTdSozs?YIWyAlUlUX.6d%M;QsEMO,", &
        "MDuyX`^owbP^(x73S,/eUVMzb;A*Z:Kg:qi,eed5TirBl:[/`?.Nj%jeH=W>>9.X2Mc#4G(38x$;XiW1-XsD(%n>GR+8_VT?lnE,8HVPUGUp4t^XZ9[,6B", &
        "0LD,(ARf*DPkS,>S,IlvZf2:w]_1oLn5_p;kwXN=,):2-hDj[WK>7I%.VCScNpjK`iQcX-@7z#;,R*WO,CUQGS83YZ`S%L.?:)OOmyys6x]v[UE0n`WRJA", &
        "YvcV:fP?.0]uam5>Eg5rFju*i(/KE1f9N[WxJnKQ/Er.Tp*fV^[;,;Sy68291W9qleT,jR+Rfd?l$W.8o#ao_CN_zV,[R6tef/IL`%?rI+x0xEi2NY53+o", &
        "8f-Pcu+=+i?us=IF^pA5b:zVI:n_bqH1Ru:1gG:D_0Do0>K9mzBaYuEXRttVw=+Nt7=PQXCs]/0o$go:v/Rfro/GQxB%w.(hEC=K-sgT;3>4f;h8TOzYJD", &
        "Xxg0`7D/_ROhL.T^na@ja,>w50`l^-q(3l$4L($lcGGrlXOgtvPdX%=54dWo_s]9f$H?V9`-.wf:]Ikp]OtO[,xABQ[CQP7)X%[3PT2u7^R7OMa^5RB?;t", &
        "XD9Sn<$;rSM2;p%t`k_cE5Dv@zM;84j0*SMGs98];%XPpGUQVaQ1dk<=kQBqiiv??nPd/Vw:V^rPlbaNj<%iAVVuLv[WQUISpE@Yoe$eYF1mdGuOrno7Bf", &
        "VS$>QzQJRv#s4;P1KFaYk;(,SnsqsoJ3lNdnQPap=s:N;TGfA,n^V:uLBExPN4G5CVSTs#6EKYIg1Hu^NT.4tQlWnh6fT)PdA<g[ntqM4cQarDdbPMqdN-", &
        "p?250nN>ZK4qtb?Mwu%T$)CX8xMw)4lpfh/+mpYnXEM6.Hr,J1g%$*8_scC<+1-(7J[%Ml8m:k*)>c?tTfT_wvV5F-RBYGXsdAgL>N#c^hn.Z:KC1o`lG2", &
        "*Gu+t+uI8AvwBS/,tRTabFcdRxS0wvzX_S.Fn;^Bf*vNq]`.,xN[d7>3nQQMZ8je><%1OWchC$WQGx5K=[0q`rl;88M<4XwTb=+XSA.X*paU`:<%jVfn4X", &
        "TyNy/FBFCEENE:;n5Q6r9nZ7-hn<=q>@dce,?N-/0TaTXdhDsC^;pIc3n0tuS#T]LPjqxNpq5A%5?JTT(c@h;2V=IpUX9Bvh:m3avsF39:]sDK0qDW=my8", &
        "KWUi2KVAqAtPY+oGiHa1C01=Myuws$J+,PjDUDT<+3F0T*15FKP(B/199*Eo:T,C-A+nTw:;CXVo+Rtj<0`:<%jVfn4DTyOrIkBR_WK,lo^55%WiZCRF8<", &
        "/G/7@*ZTG9z`Oq1ipP-KLym9B4NfBOby1YKY;L<tqkAHTeS6ac[62mpq8RB^$?sh;3DW;0gTT@<kH>OqeaXNc%M-@#xyTl+/u.W8+D5PEogg1Nn)TOK+_a", &
        "9YGOZMFudNSW;4BTvM$lUx<[1#x<[1#x<Z#[#####(u]ir#$b05#$baDvyPc)x;t.:$%_[q]]^zP[zkD1E/Pj<$l++j3nhEGg/jTJ[8g]g46`)Vj:arF,V", &
        ">9i]dHUHB%B9#+r_pME_Wl0q>pG/cqmwhoaT//HP6>g5;IE`]J7Qif+L=mmprX#o3cyYocl5HB%9=R+c-Ip-:00afd=5)Y3J$:gubF3M,K39UH4[^VX4c[", &
        ";t>fFAy_3/bZ5qgocm?=B%9>STt(o-]]eqM@Z1pN]c9ec(#(A84LdhWf^#]`9:^ksHO*itNDW)OUodS_VYIx#[U%EaR%b1;CK]R/AIc]s-q?]ZF[$?#Q0X", &
        "cD`+zrs;HkLu??2T:8_(s*=2Khx;`0h%Z%A4]FCuTaePewOg.H<r?,@r8ZPLdEvoQ2pq,+[1JS(@+7gQ2R9hBFa0yi0p4YCs-@uPk0g+Ch=;;gjzGsSwKX", &
        "R+DG?K.+Z3z?xj,r=dx<lTg3jQE)EftyhuES-vl2c6fP3Trrr=[A>HUw]UJW_W6bhMt8jJ)Y=u_T(AC<y::$02Q61?aFO$I-s-as9i8,bq?Ck_#2Ft9d^_", &
        "?Xl@FE?J0=h(j0Rk(hI/RJ$6XF[QblA+exm<3-hD>czc#O;9Tu/)=%NaTi)#GcA:,PkIvX`#(]z;7CW^3A]=3)0f,a+#+53C<P4Lo0f,dIT$CuPubtqG<P", &
        "4Lo0f,dISu3b/n)O^7NZ]dG/uk05183@x<8sN=:@p3t+.<l`+6^96W@CKmT$C%B/ao?K>YQKN$?+,D0dDW3;kpk=<P4Lo0WY:T$ZI%G<P4Lo0f,dIT#Sfr", &
        "0f,dIT$Cuc<P0<^.+nRm/Y=abdd-l^:X0pehSjI[OWKJFONbNbe*4nf/l.-V<P4LB0$)3]0f,`z"]

    character(len=118), parameter :: BLOB_ROWS(286) = [ &
        BLOB_ROWS_1, &
        BLOB_ROWS_2, &
        BLOB_ROWS_3]

end module fplotlib_glyphs_data
