! fplotlib_colors — matplotlib's named colors.
!
! Generated by tools/gen_colors.py; do not edit by hand. Holds the CSS4/X11
! names plus matplotlib's "tab:" family, which are accepted anywhere a
! color is taken.
module fplotlib_colors
    implicit none
    private

    public :: color_from_name

    integer, parameter :: NCOLOR = 158
    integer, parameter :: NAMELEN = 20

    character(len=NAMELEN), parameter :: NAMES(NCOLOR) = [ character(len=NAMELEN) :: &
        "aliceblue"           , "antiquewhite"        , "aqua"                , "aquamarine"          , &
        "azure"               , "beige"               , "bisque"              , "black"               , &
        "blanchedalmond"      , "blue"                , "blueviolet"          , "brown"               , &
        "burlywood"           , "cadetblue"           , "chartreuse"          , "chocolate"           , &
        "coral"               , "cornflowerblue"      , "cornsilk"            , "crimson"             , &
        "cyan"                , "darkblue"            , "darkcyan"            , "darkgoldenrod"       , &
        "darkgray"            , "darkgreen"           , "darkgrey"            , "darkkhaki"           , &
        "darkmagenta"         , "darkolivegreen"      , "darkorange"          , "darkorchid"          , &
        "darkred"             , "darksalmon"          , "darkseagreen"        , "darkslateblue"       , &
        "darkslategray"       , "darkslategrey"       , "darkturquoise"       , "darkviolet"          , &
        "deeppink"            , "deepskyblue"         , "dimgray"             , "dimgrey"             , &
        "dodgerblue"          , "firebrick"           , "floralwhite"         , "forestgreen"         , &
        "fuchsia"             , "gainsboro"           , "ghostwhite"          , "gold"                , &
        "goldenrod"           , "gray"                , "green"               , "greenyellow"         , &
        "grey"                , "honeydew"            , "hotpink"             , "indianred"           , &
        "indigo"              , "ivory"               , "khaki"               , "lavender"            , &
        "lavenderblush"       , "lawngreen"           , "lemonchiffon"        , "lightblue"           , &
        "lightcoral"          , "lightcyan"           , "lightgoldenrodyellow", "lightgray"           , &
        "lightgreen"          , "lightgrey"           , "lightpink"           , "lightsalmon"         , &
        "lightseagreen"       , "lightskyblue"        , "lightslategray"      , "lightslategrey"      , &
        "lightsteelblue"      , "lightyellow"         , "lime"                , "limegreen"           , &
        "linen"               , "magenta"             , "maroon"              , "mediumaquamarine"    , &
        "mediumblue"          , "mediumorchid"        , "mediumpurple"        , "mediumseagreen"      , &
        "mediumslateblue"     , "mediumspringgreen"   , "mediumturquoise"     , "mediumvioletred"     , &
        "midnightblue"        , "mintcream"           , "mistyrose"           , "moccasin"            , &
        "navajowhite"         , "navy"                , "oldlace"             , "olive"               , &
        "olivedrab"           , "orange"              , "orangered"           , "orchid"              , &
        "palegoldenrod"       , "palegreen"           , "paleturquoise"       , "palevioletred"       , &
        "papayawhip"          , "peachpuff"           , "peru"                , "pink"                , &
        "plum"                , "powderblue"          , "purple"              , "rebeccapurple"       , &
        "red"                 , "rosybrown"           , "royalblue"           , "saddlebrown"         , &
        "salmon"              , "sandybrown"          , "seagreen"            , "seashell"            , &
        "sienna"              , "silver"              , "skyblue"             , "slateblue"           , &
        "slategray"           , "slategrey"           , "snow"                , "springgreen"         , &
        "steelblue"           , "tab:blue"            , "tab:brown"           , "tab:cyan"            , &
        "tab:gray"            , "tab:green"           , "tab:olive"           , "tab:orange"          , &
        "tab:pink"            , "tab:purple"          , "tab:red"             , "tan"                 , &
        "teal"                , "thistle"             , "tomato"              , "turquoise"           , &
        "violet"              , "wheat"               , "white"               , "whitesmoke"          , &
        "yellow"              , "yellowgreen"          ]

    character(len=7), parameter :: HEXES(NCOLOR) = [ character(len=7) :: &
        "#f0f8ff", "#faebd7", "#00ffff", "#7fffd4", "#f0ffff", "#f5f5dc", &
        "#ffe4c4", "#000000", "#ffebcd", "#0000ff", "#8a2be2", "#a52a2a", &
        "#deb887", "#5f9ea0", "#7fff00", "#d2691e", "#ff7f50", "#6495ed", &
        "#fff8dc", "#dc143c", "#00ffff", "#00008b", "#008b8b", "#b8860b", &
        "#a9a9a9", "#006400", "#a9a9a9", "#bdb76b", "#8b008b", "#556b2f", &
        "#ff8c00", "#9932cc", "#8b0000", "#e9967a", "#8fbc8f", "#483d8b", &
        "#2f4f4f", "#2f4f4f", "#00ced1", "#9400d3", "#ff1493", "#00bfff", &
        "#696969", "#696969", "#1e90ff", "#b22222", "#fffaf0", "#228b22", &
        "#ff00ff", "#dcdcdc", "#f8f8ff", "#ffd700", "#daa520", "#808080", &
        "#008000", "#adff2f", "#808080", "#f0fff0", "#ff69b4", "#cd5c5c", &
        "#4b0082", "#fffff0", "#f0e68c", "#e6e6fa", "#fff0f5", "#7cfc00", &
        "#fffacd", "#add8e6", "#f08080", "#e0ffff", "#fafad2", "#d3d3d3", &
        "#90ee90", "#d3d3d3", "#ffb6c1", "#ffa07a", "#20b2aa", "#87cefa", &
        "#778899", "#778899", "#b0c4de", "#ffffe0", "#00ff00", "#32cd32", &
        "#faf0e6", "#ff00ff", "#800000", "#66cdaa", "#0000cd", "#ba55d3", &
        "#9370db", "#3cb371", "#7b68ee", "#00fa9a", "#48d1cc", "#c71585", &
        "#191970", "#f5fffa", "#ffe4e1", "#ffe4b5", "#ffdead", "#000080", &
        "#fdf5e6", "#808000", "#6b8e23", "#ffa500", "#ff4500", "#da70d6", &
        "#eee8aa", "#98fb98", "#afeeee", "#db7093", "#ffefd5", "#ffdab9", &
        "#cd853f", "#ffc0cb", "#dda0dd", "#b0e0e6", "#800080", "#663399", &
        "#ff0000", "#bc8f8f", "#4169e1", "#8b4513", "#fa8072", "#f4a460", &
        "#2e8b57", "#fff5ee", "#a0522d", "#c0c0c0", "#87ceeb", "#6a5acd", &
        "#708090", "#708090", "#fffafa", "#00ff7f", "#4682b4", "#1f77b4", &
        "#8c564b", "#17becf", "#7f7f7f", "#2ca02c", "#bcbd22", "#ff7f0e", &
        "#e377c2", "#9467bd", "#d62728", "#d2b48c", "#008080", "#d8bfd8", &
        "#ff6347", "#40e0d0", "#ee82ee", "#f5deb3", "#ffffff", "#f5f5f5", &
        "#ffff00", "#9acd32" ]

contains

    ! Returns the #rrggbb for a name, or an empty string if unknown, so the
    ! caller can fall back to the other color spellings.
    pure function color_from_name(s) result(col)
        character(len=*), intent(in) :: s
        character(len=7) :: col
        integer :: lo, hi, mid, c
        character(len=NAMELEN) :: key

        col = ""
        if (len_trim(s) > NAMELEN) return
        key = lower(trim(s))
        lo = 1
        hi = NCOLOR
        do while (lo <= hi)
            mid = (lo + hi) / 2
            c = compare(key, NAMES(mid))
            if (c == 0) then
                col = HEXES(mid)
                return
            else if (c < 0) then
                hi = mid - 1
            else
                lo = mid + 1
            end if
        end do
    end function color_from_name

    pure function compare(a, b) result(c)
        character(len=*), intent(in) :: a, b
        integer :: c
        if (a < b) then
            c = -1
        else if (a > b) then
            c = 1
        else
            c = 0
        end if
    end function compare

    pure function lower(s) result(t)
        character(len=*), intent(in) :: s
        character(len=NAMELEN) :: t
        integer :: i, k
        t = ""
        do i = 1, min(len(s), NAMELEN)
            k = iachar(s(i:i))
            if (k >= 65 .and. k <= 90) k = k + 32
            t(i:i) = achar(k)
        end do
    end function lower

end module fplotlib_colors
